---
# TODO check if selinux is here ?
- name: Deploy the pam configuration
  lineinfile:
    dest: "/etc/pam.d/{{ item }}"
    line: "{{ namespace_line }}"
  with_items: "{{ pam_files[ansible_os_family] }}"

- copy: dest=/etc/security/namespace.d/tmp.conf src=tmp.conf
